CREATE TABLE clients (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, email VARCHAR(40) NOT NULL,
	password VARCHAR(40) NOT NULL, name VARCHAR(20) NOT NULL, lastname VARCHAR(30) NOT NULL, 
	birthdate DATE NOT NULL, sex VARCHAR(1) NOT NULL, phone VARCHAR(12) NOT NULL);

CREATE CONSTRAINT clients UNIQUE (email);
